### ISSUE TITLE
Adding fields to the table and methods to the model of Yii 2-User Extension

### ISSUE THREAD

**Issue by aidonsnous** [cinghie/yii2-user-extended#1]
While looking for an extension that will simplify things, I find this yii2-user.dmeroff.ru/docs - Dektrium project and would like to add what are important for me miss in the model and table.

First of all , I have my user table(model) in my database but after
passing throught your extension I found it coul really help me but the
problem I have is in my table a part from user id(user may use it to login to), name,email,profile
photo(for comment(thumbnail) and profile) and password field I have
also gender,telephone number(which the user can use to log in) and my
user model has other methods too. how can I handle that using your
extension?

Secondly, I want to put the log in view and sign up view at the same
time on the main layout(kind of using them as blocks), How can I do
that?

Does it support Internationalization?how?

**Comment by cinghie** [comment]
To work properly my extension needs you start the migration from the following link: https://github.com/cinghie/yii2-user-extended#3-update-yii2-user-extended-database-schema.

This migration add to database profile table firstname, lastname, birthday, terms and avatar.

To customize the login page by adding the recording you can do an override of the code.

To override the model you have to add to the config file, in the module section, something like this:

```
'user' => [ 
       // Yii2 User Models Overrides
      'modelMap' => [
            'RegistrationForm' => 'THE_PATH_TO_YOUR_CODE\models\RegistrationForm',
      ]
]
```

To Override the view you have to add to the config file, in the component section, something like this:

```
// Yii2 User Extended
        'view' => [
            'theme' => [
                'pathMap' => [
                    '@dektrium/user/views/registration' => 'THE_PATH_TO_YOUR_CODE/views/registration',
                ],
            ],
        ],
```

The extension support Internationalization

**Comment by aidonsnous** [comment]
Thanks a lot cinghie; So does it also support user management web interface(RBAC) as Yii 2 user extension?

**Comment by cinghie** [comment]
For now this extension does not support RBAC by default, but I planned to add in a future release. You can add this manually to your yii2 project

**Comment by aidonsnous** [comment]
Thanks so much for the extension

**Comment by cinghie** [comment]
You're welcome
