### ISSUE TITLE
Calling unknown method: cinghie\yii2userextended\controllers\AdminController::getUserEvent()

### ISSUE THREAD

**Issue by tommyblink182** [cinghie/yii2-user-extended#3]
Hi,
When I try to lock the user through the Route, "user/admin/index" appears the error noted in the title of the issue.

I believe that the specified method does not exist.
Can you kindly give me some pointers on how to fix.
Thank you

**Comment by cinghie** [comment]
Have you override the AdminController of Yii2 User like explein in [https://github.com/cinghie/yii2-user-extended#5-set-configuration-file](https://github.com/cinghie/yii2-user-extended#5-set-configuration-file)

**Comment by tommyblink182** [comment]
I already configured the form as indicated. First did not give me this error, since I did the update I get the error.
Use the advanced template with the changes mentioned in the Guide.

**Comment by cinghie** [comment]
Sorry but i don't have the same issue on a yii2 advanced template. 

Do you have the last Yii2 user version (dev)?

**Comment by tommyblink182** [comment]
I have Yii2 => 2.0.7

**Comment by cinghie** [comment]
Not Yii2 Version but Yii2 User Version (Dektrium Extension): i think you have an old version or a stable version that not support getUserEvent().

Try to update Yii2 User by Dektrium to last "dev" version

**Comment by tommyblink182** [comment]
Thanks, fixed
