### ISSUE TITLE
Не могу зайти в интерфейс управления пользователями.

### ISSUE THREAD

**Issue by qwerty1966** [cinghie/yii2-user-extended#5]
Доброго времени суток.Установил cinghie не могу зайти в интерфейс управления пользователями. http://joxi.ru/l2ZEbNVS18w1mJ , на Dektrium/Rbac проблем не было,подскажите что не так.вот конфиг 

[web.txt](https://github.com/cinghie/yii2-user-extended/files/703531/web.txt)

**Comment by cinghie** [comment]
hi qwerty1966,

please write in english, i don't know russian language

**Comment by qwerty1966** [comment]
(I will try. But I do not speak English for five)
 Good time of day. I installed the extension Singh all works, but I can not go to the user management interface http://joxi.ru/l2ZEbNVS18w1mJ~~pobj, on Dektrium / RBAC not had any problems, tell me what is wrong or what to do .
The second question is how to disable checking JS mandatory fields of the ? I tried to comment out reguired and remove fields in the form, but it caused a chain of errors, had to reinstall again.
My task is to leave in the form of registration only email, password confirmation password, login and captcha. The other fields should be filled through the profile.
here are my configuration .
[web.txt](https://github.com/cinghie/yii2-user-extended/files/704951/web.txt)
[RegistrationForm.txt](https://github.com/cinghie/yii2-user-extended/files/705688/RegistrationForm.txt)

Waiting for your reply.

**Comment by cinghie** [comment]
I @qwerty1966,

i think you can't access to the user manangement because your user is not 'admin'.
You have to add admin rule it.

To customize your form registration you have to copy and modify the form view and controller and override the Yii2 User in configuration
