### ISSUE TITLE
Setting unknown property: cinghie\userextended\Module::avatar

### ISSUE THREAD

**Issue by ghost** [cinghie/yii2-user-extended#8]
I have followed all the instructions yet failed to get this running. I receive a error
Setting unknown property: cinghie\userextended\Module::avatar

I have all the database tables installed properly. I have img folder in the root with 777 permissions. Profile table has avatar field added. I also added all the config mentioned.

Any Help?

**Comment by cinghie** [comment]
Hi @shrikanth003 

do you have the last dev version?

It seems to be no avatar variable in the Module file; i think do you have an old version.
Do a composer update
